name: xwordle
description: The wordle game for Telegram. Inspired by the original Wordle game by NY Times.
version: 1.1.1
repository: https://github.com/heysreelal/xwordle
publish_to: "none"

environment:
  sdk: ^3.0.4

dependencies:
  http: ^1.0.0
  televerse:
    git:
      url: https://github.com/HeySreelal/televerse/
      ref: dev
    version: 1.17.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
