name: xwordle
description: The wordle game for Telegram. Inspired by the original Wordle game by NY Times.
version: 1.3.2
repository: https://github.com/heysreelal/xwordle
publish_to: "none"

environment:
  sdk: ^3.0.4

dependencies:
  http: ^1.0.0
  televerse: ^1.21.1
  dart_firebase_admin: ^0.3.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
